### ISSUE TITLE
Elements table view broken in version 1.0.0

### ISSUE THREAD

**Issue by Pohli** [Aspor/harbour-jaksari#12]
![Screenshot_20190828_001](https://user-images.githubusercontent.com/26346589/63872912-e84f6f80-c9be-11e9-83df-f73898964dce.png)

Jolla Phone with SFOS 3.0.1.11

**Comment by Aspor** [comment]
Hmm seems that default font size doesn't scale with screen size and font size needs to be defined with screen size. Should be simple to fix.

**Comment by Pohli** [comment]
Now it looks nice again, thanks!
