### ISSUE TITLE
Wrong unit of density

### ISSUE THREAD

**Issue by Pohli** [Aspor/harbour-jaksari#8]
Density values are given in g/cm3, not in g/L. This mistake comes from the source project Periodic-Table-JSON. I already filled an issue there, too.

**Comment by Aspor** [comment]
Actually density values are  apparently given g/l for gases and g/cm³ for solids and liquids. Issue has been fixed in Jaksari but new version probably won't get through Harbour QA before Monday. Updated version can be found in OpenRepos.x

**Comment by Pohli** [comment]
Thanks, that was quick!
